### ISSUE TITLE
Set up database connection

### ISSUE THREAD

**Issue by EstherDGoldstein** [NOAA-Fisheries-AFSC-Age-and-Growth/nir-spectroscopy#1]
-Need to set up the connection to AGE3 database @MorganArrington-NOAA @EstherDGoldstein 
-Check that I did rm(list=ls()) correctly @EstherDGoldstein 
-Check that Tango spectra match those from .spc OPUS macro without offset and that cubic interpolation looks good

**Comment by MorganArrington-NOAA** [comment]
@EstherDGoldstein for some reason I never got an email notification about this issue! Just seeing it now because I opened up GitHub. Just added to my to-do list.

**Comment by MorganArrington-NOAA** [comment]
@EstherDGoldstein added code for DB connect that I used for connecting to and querying RACEBASE. This will need to get edited for our use but hopefully helpful as a starting point.
